import type { CookieRecord } from "./model";
import type { CookieScope } from "./target";

export type ExportFormatId = "json" | "netscape" | "header" | "csv";

export interface ExportFormatDefinition {
  id: ExportFormatId;
  label: string;
  description: string;
  extension: string;
  mimeType: string;
  lossy: boolean;
}

export interface ExportContext {
  exportedAt: Date;
  modifiedCookieCount: number;
  scope: CookieScope;
  siteDomain: string;
  sourceUrl: string;
}

export const EXPORT_FORMATS: readonly ExportFormatDefinition[] = [
  {
    id: "json",
    label: "JSON（完整字段）",
    description: "保留扩展 API 返回的属性，适合备份和二次处理。",
    extension: "json",
    mimeType: "application/json;charset=utf-8",
    lossy: false
  },
  {
    id: "netscape",
    label: "Netscape cookies.txt",
    description: "兼容 curl、wget、yt-dlp 等工具；部分现代属性无法表示。",
    extension: "txt",
    mimeType: "text/plain;charset=utf-8",
    lossy: true
  },
  {
    id: "header",
    label: "Cookie 请求头",
    description: "生成一行 Cookie: name=value；不包含 Domain、Path 等属性。",
    extension: "txt",
    mimeType: "text/plain;charset=utf-8",
    lossy: true
  },
  {
    id: "csv",
    label: "CSV 表格",
    description: "将 Cookie 属性按列展开，适合人工检查和表格处理。",
    extension: "csv",
    mimeType: "text/csv;charset=utf-8",
    lossy: false
  }
] as const;

export function getExportFormat(formatId: ExportFormatId): ExportFormatDefinition {
  const format = EXPORT_FORMATS.find((candidate) => candidate.id === formatId);

  if (!format) {
    throw new Error("Unsupported export format: " + formatId);
  }

  return format;
}

export function serializeCookies(
  formatId: ExportFormatId,
  cookies: readonly CookieRecord[],
  context: ExportContext
): string {
  switch (formatId) {
    case "json":
      return serializeJson(cookies, context);
    case "netscape":
      return serializeNetscape(cookies, context);
    case "header":
      return serializeHeader(cookies, context);
    case "csv":
      return serializeCsv(cookies);
  }
}

function serializeJson(cookies: readonly CookieRecord[], context: ExportContext): string {
  return (
    JSON.stringify(
      {
        schema: "script-toolbox.cookie-exporter",
        schemaVersion: 3,
        exportedAt: context.exportedAt.toISOString(),
        sourceUrl: context.sourceUrl,
        scope: context.scope,
        siteDomain: context.siteDomain,
        modifiedCookieCount: context.modifiedCookieCount,
        cookieCount: cookies.length,
        cookies
      },
      null,
      2
    ) + "\n"
  );
}

function serializeNetscape(cookies: readonly CookieRecord[], context: ExportContext): string {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by Script Toolbox Cookie Exporter at " + context.exportedAt.toISOString(),
    "# Source: " + context.sourceUrl,
    "# Scope: " + context.scope,
    "# Site domain: " + context.siteDomain,
    "# Edited snapshot cookies: " + context.modifiedCookieCount,
    "# This file contains sensitive authentication data.",
    "# SameSite, partition key, store ID, and host-only metadata may be lossy.",
    ""
  ];

  for (const cookie of cookies) {
    const baseDomain = sanitizeNetscapeField(cookie.domain);
    const domain = cookie.httpOnly ? "#HttpOnly_" + baseDomain : baseDomain;
    const includeSubdomains = cookie.hostOnly ? "FALSE" : "TRUE";
    const secure = cookie.secure ? "TRUE" : "FALSE";
    const expiration = cookie.session ? "0" : String(Math.trunc(cookie.expirationDate ?? 0));

    lines.push(
      [
        domain,
        includeSubdomains,
        sanitizeNetscapeField(cookie.path),
        secure,
        expiration,
        sanitizeNetscapeField(cookie.name),
        sanitizeNetscapeField(cookie.value)
      ].join("\t")
    );
  }

  return lines.join("\n") + "\n";
}

function serializeHeader(
  cookies: readonly CookieRecord[],
  context: ExportContext
): string {
  if (context.scope !== "url") {
    throw new Error("Cookie 请求头只适用于“当前 URL”范围。");
  }

  const pairs = cookies.map((cookie) => cookie.name + "=" + cookie.value);
  return "Cookie: " + pairs.join("; ") + "\n";
}

function serializeCsv(cookies: readonly CookieRecord[]): string {
  const columns: ReadonlyArray<readonly [string, (cookie: CookieRecord) => string]> = [
    ["name", (cookie) => cookie.name],
    ["value", (cookie) => cookie.value],
    ["domain", (cookie) => cookie.domain],
    ["path", (cookie) => cookie.path],
    ["secure", (cookie) => String(cookie.secure)],
    ["httpOnly", (cookie) => String(cookie.httpOnly)],
    ["sameSite", (cookie) => cookie.sameSite],
    ["session", (cookie) => String(cookie.session)],
    [
      "expirationDate",
      (cookie) => (cookie.expirationDate === undefined ? "" : String(cookie.expirationDate))
    ],
    ["hostOnly", (cookie) => String(cookie.hostOnly)],
    ["storeId", (cookie) => cookie.storeId],
    ["partitionTopLevelSite", (cookie) => cookie.partitionKey?.topLevelSite ?? ""],
    [
      "partitionHasCrossSiteAncestor",
      (cookie) =>
        cookie.partitionKey?.hasCrossSiteAncestor === undefined
          ? ""
          : String(cookie.partitionKey.hasCrossSiteAncestor)
    ]
  ];

  const lines = [
    columns.map(([heading]) => escapeCsvCell(heading)).join(","),
    ...cookies.map((cookie) =>
      columns.map(([, getValue]) => escapeCsvCell(getValue(cookie))).join(",")
    )
  ];

  return lines.join("\r\n") + "\r\n";
}

function sanitizeNetscapeField(value: string): string {
  return value
    .replace(/\t/g, "%09")
    .replace(/\r/g, "%0D")
    .replace(/\n/g, "%0A");
}

function escapeCsvCell(value: string): string {
  return '"' + value.replace(/"/g, '""') + '"';
}
